name: azulzinho
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  file_selector: ^1.0.3
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get_it: ^7.6.8
  #  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  path_provider: ^2.1.2
  screenshot: ^2.3.0
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  # time_machine: ^0.9.17

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
